language: cpp
sudo: required

branches:
  only:
    - osx

cache:
  ccache: true
  directories:
    - .ccache
    - ${TRAVIS_BUILD_DIR}/deps

python:
  - "3.5"

matrix:
  fast_finish: true
  include:
    - compiler: clang
      os: osx
      osx_image: xcode7.3
      env: LDIST=-osx_10.11
    - compiler: clang
      os: osx
      osx_image: xcode8.3
      env: LDIST=-osx_10.12
    - compiler: gcc
      os: linux
      dist: trusty
      env: LDIST=-trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/travis/before_install_darwin.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/travis/before_install_linux.sh ; fi

  - mkdir -p ${TRAVIS_BUILD_DIR}/build

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_darwin.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/make_linux.sh ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ${TRAVIS_BUILD_DIR}/build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ${TRAVIS_BUILD_DIR}/CI/travis/package_darwin.sh; fi


notifications:
  email:
    on_success: change
    on_failure: always

before_deploy:
  - . ${TRAVIS_BUILD_DIR}/CI/travis/before_deploy.sh
