name: Scopy armhf AppImage Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-20.04
  USERNAME: github-actions

jobs:

  build_scopy_armhf_appimage:
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v4
          with:
                set-safe-directory: 'true'

        - name: Pull the Docker Image
          run: docker pull cristianbindea/scopy2-armhf-appimage:latest

        - name: Create Scopy AppImage
          shell: bash
          run: |
                cd $GITHUB_WORKSPACE
                sudo apt update
                ./ci/armhf/create_sysroot.sh install_packages install_qemu
                ./ci/armhf/armhf_build_process.sh generate_ci_envs

                docker run \
                        --mount type=bind,source="$GITHUB_WORKSPACE",target=/home/runner/scopy \
                        --env-file $GITHUB_WORKSPACE/ci/general/gh-actions.envs \
                        cristianbindea/scopy2-armhf-appimage:latest \
                        /bin/bash -c    'cd $HOME && \
                                        sudo chown -R runner:runner scopy && \
                                        cd $HOME/scopy && \
                                        ./ci/armhf/armhf_build_process.sh install_packages download_cmake download_crosscompiler move_sysroot build_scopy build_iio-emu create_appdir create_appimage move_appimage
                                        '
        - name: Set short git commit SHA
          shell: bash
          run: echo "commit_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_ENV"

        - uses: actions/upload-artifact@v4
          with:
            name: scopy-linux-armhf-${{ env.commit_sha }}
            path: ${{ github.workspace }}/Scopy-armhf.AppImage
