name: Scopy armhf AppImage Build

on: [push, pull_request]

env:
  BUILD_HOST: ubuntu-22.04
  USERNAME: github-actions

jobs:
  docker_tag_workflow:
    uses: ./.github/workflows/get_docker_tag.yml

  build_scopy_armhf_appimage:
    runs-on: ubuntu-22.04
    needs: docker_tag_workflow
    steps:
        - uses: actions/checkout@v4
          with:
                set-safe-directory: 'true'
                fetch-depth: '0'

        - name: Pull the Docker Image
          run: docker pull cristianbindea/scopy2-armhf-appimage:${{ needs.docker_tag_workflow.outputs.docker_tag }}

        - name: Create Scopy AppImage
          shell: bash
          run: |
                cd $GITHUB_WORKSPACE
                sudo apt update
                ./ci/arm/create_sysroot.sh arm32 install_packages install_qemu
                ./ci/arm/arm_build_process.sh arm32 generate_ci_envs

                docker run \
                        --mount type=bind,source="$GITHUB_WORKSPACE",target=/home/runner/scopy \
                        --env-file $GITHUB_WORKSPACE/ci/general/gh-actions.envs \
                        cristianbindea/scopy2-armhf-appimage:${{ needs.docker_tag_workflow.outputs.docker_tag }} \
                        /bin/bash -c    'cd $HOME && \
                                        sudo chown -R runner:runner scopy && \
                                        cd $HOME/scopy && \
                                        ./ci/arm/arm_build_process.sh arm32 install_packages move_tools move_sysroot build_scopy build_iio-emu create_appdir create_appimage move_appimage
                                        '
        - name: Set short git commit SHA
          shell: bash
          run: echo "commit_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_ENV"

        - uses: actions/upload-artifact@v4
          with:
            name: scopy-linux-armhf-${{ env.commit_sha }}
            path: ${{ github.workspace }}/Scopy-armhf.AppImage
